apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-bphn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hkep-tenant/rhtap-demo-app/hacbs-test-project-bphn@sha256:82bf78b765773f763f66cbbf055728e350b2adfa66668f5698e6fc5dbea7add9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
